# -*- coding: utf-8 -*-

WORD_BANK = [
    ("abandon", "v. 放弃；遗弃", "əˈbændən"),
    ("ability", "n. 能力；才智", "əˈbɪlɪti"),
    ("abnormal", "adj. 反常的；异常的", "æbˈnɔːrml"),
    ("aboard", "adv./prep. 在船(车、飞机)上", "əˈbɔːrd"),
    ("abolish", "v. 废除；取消", "əˈbɒlɪʃ"),
    ("absent", "adj. 缺席的；心不在焉的", "ˈæbsənt"),
    ("absolute", "adj. 绝对的；完全的", "ˈæbsəluːt"),
    ("absorb", "v. 吸收；吸引", "əbˈzɔːrb"),
    ("abstract", "adj. 抽象的 n. 摘要", "ˈæbstrækt"),
    ("abundant", "adj. 丰富的；充裕的", "əˈbʌndənt"),
    ("abuse", "v./n. 滥用；虐待", "əˈbjuːz"),
    ("academic", "adj. 学术的；学业的", "ˌækəˈdemɪk"),
    ("accelerate", "v. 加速；促进", "əkˈseləreɪt"),
    ("access", "n. 通道；进入 v. 存取", "ˈækses"),
    ("accommodate", "v. 容纳；提供住宿", "əˈkɒmədeɪt"),
    ("accompany", "v. 陪伴；伴随", "əˈkʌmpəni"),
    ("accomplish", "v. 完成；实现", "əˈkʌmplɪʃ"),
    ("accord", "n./v. 一致；协议", "əˈkɔːrd"),
    ("account", "n. 账户；描述 v. 解释", "əˈkaʊnt"),
    ("accumulate", "v. 积累；堆积", "əˈkjuːmjəleɪt"),
    ("accurate", "adj. 精确的；准确的", "ˈækjərɪt"),
    ("accuse", "v. 指控；指责", "əˈkjuːz"),
    ("achieve", "v. 完成；达到", "əˈtʃiːv"),
    ("acknowledge", "v. 承认；致谢", "əkˈnɒlɪdʒ"),
    ("acquire", "v. 获得；学到", "əˈkwaɪər"),
    ("adapt", "v. 适应；改编", "əˈdæpt"),
    ("adequate", "adj. 足够的；适当的", "ˈædɪkwət"),
    ("adjust", "v. 调整；适应", "əˈdʒʌst"),
    ("administration", "n. 管理；行政", "ədˌmɪnɪˈstreɪʃn"),
    ("admire", "v. 钦佩；赞赏", "ədˈmaɪər"),
    ("admit", "v. 承认；准许进入", "ədˈmɪt"),
    ("adopt", "v. 采用；收养", "əˈdɒpt"),
    ("advance", "v./n. 前进；进步", "ədˈvɑːns"),
    ("advantage", "n. 优势；有利条件", "ədˈvɑːntɪdʒ"),
    ("adventure", "n. 冒险；奇遇", "ədˈventʃər"),
    ("advertise", "v. 做广告；宣传", "ˈædvərtaɪz"),
    ("advocate", "v. 提倡 n. 提倡者", "ˈædvəkeɪt"),
    ("affect", "v. 影响；感动", "əˈfekt"),
    ("afford", "v. 买得起；提供", "əˈfɔːrd"),
    ("aggressive", "adj. 侵略的；好斗的", "əˈɡresɪv"),
    ("agriculture", "n. 农业；农学", "ˈæɡrɪkʌltʃər"),
    ("aid", "n./v. 援助；帮助", "eɪd"),
    ("alarm", "n. 警报；惊慌", "əˈlɑːrm"),
    ("alert", "adj. 警觉的 n. 警报", "əˈlɜːrt"),
    ("alliance", "n. 联盟；同盟", "əˈlaɪəns"),
    ("allowance", "n. 津贴；零用钱", "əˈlaʊəns"),
    ("alter", "v. 改变；修改", "ˈɔːltər"),
    ("alternative", "n. 替代品 adj. 可替代的", "ɔːlˈtɜːrnətɪv"),
    ("ambition", "n. 雄心；抱负", "æmˈbɪʃn"),
    ("ambulance", "n. 救护车", "ˈæmbjələns"),
    ("amend", "v. 修正；修改", "əˈmend"),
    ("amount", "n. 数量 v. 总计", "əˈmaʊnt"),
    ("ample", "adj. 充足的；宽敞的", "ˈæmpl"),
    ("analyze", "v. 分析", "ˈænəlaɪz"),
    ("ancestor", "n. 祖先；先辈", "ˈænsestər"),
    ("anchor", "n. 锚 v. 抛锚", "ˈæŋkər"),
    ("annual", "adj. 每年的 n. 年刊", "ˈænjuəl"),
    ("anticipate", "v. 预期；期望", "ænˈtɪsɪpeɪt"),
    ("anxiety", "n. 焦虑；渴望", "æŋˈzaɪəti"),
    ("apart", "adv. 分离；分开", "əˈpɑːrt"),
    ("apologize", "v. 道歉", "əˈpɒlədʒaɪz"),
    ("apparent", "adj. 明显的；表面上的", "əˈpærənt"),
    ("appeal", "v./n. 呼吁；吸引", "əˈpiːl"),
    ("appetite", "n. 食欲；欲望", "ˈæpɪtaɪt"),
    ("appliance", "n. 器具；家用电器", "əˈplaɪəns"),
    ("apply", "v. 申请；应用", "əˈplaɪ"),
    ("appoint", "v. 任命；约定", "əˈpɔɪnt"),
    ("appreciate", "v. 感激；欣赏", "əˈpriːʃieɪt"),
    ("approach", "v./n. 接近；方法", "əˈprəʊtʃ"),
    ("appropriate", "adj. 适当的；恰当的", "əˈprəʊprɪət"),
    ("approve", "v. 批准；赞成", "əˈpruːv"),
    ("arbitrary", "adj. 任意的；武断的", "ˈɑːrbɪtreri"),
    ("architecture", "n. 建筑；建筑学", "ˈɑːrkɪtektʃər"),
    ("argue", "v. 争论；辩论", "ˈɑːrɡjuː"),
    ("arise", "v. 出现；产生", "əˈraɪz"),
    ("arrange", "v. 安排；整理", "əˈreɪndʒ"),
    ("arrest", "v./n. 逮捕；拘留", "əˈrest"),
    ("artificial", "adj. 人工的；虚伪的", "ˌɑːrtɪˈfɪʃl"),
    ("ascend", "v. 上升；攀登", "əˈsend"),
    ("aspect", "n. 方面；外观", "ˈæspekt"),
    ("assemble", "v. 集合；组装", "əˈsembl"),
    ("assert", "v. 断言；主张", "əˈsɜːrt"),
    ("assess", "v. 评估；评定", "əˈses"),
    ("asset", "n. 资产；优点", "ˈæset"),
    ("assign", "v. 分配；指派", "əˈsaɪn"),
    ("assist", "v. 帮助；协助", "əˈsɪst"),
    ("associate", "v. 联系；关联", "əˈsəʊʃieɪt"),
    ("assume", "v. 假设；承担", "əˈsjuːm"),
    ("assure", "v. 保证；使确信", "əˈʃʊər"),
    ("atmosphere", "n. 大气；气氛", "ˈætməsfɪər"),
    ("attach", "v. 附上；依恋", "əˈtætʃ"),
    ("attain", "v. 达到；获得", "əˈteɪn"),
    ("attempt", "v./n. 尝试；企图", "əˈtempt"),
    ("attend", "v. 出席；照顾", "əˈtend"),
    ("attitude", "n. 态度；看法", "ˈætɪtjuːd"),
    ("attract", "v. 吸引；引起", "əˈtrækt"),
    ("attribute", "v. 归因于 n. 属性", "əˈtrɪbjuːt"),
    ("authority", "n. 权威；当局", "ɔːˈθɒrɪti"),
    ("automatic", "adj. 自动的", "ˌɔːtəˈmætɪk"),
    ("available", "adj. 可用的；有空的", "əˈveɪləbl"),
    ("average", "adj. 平均的 n. 平均数", "ˈævərɪdʒ"),
    ("avoid", "v. 避免；躲避", "əˈvɔɪd"),
    ("award", "n. 奖品 v. 授予", "əˈwɔːrd"),
    ("aware", "adj. 意识到的", "əˈweər"),
    ("awful", "adj. 糟糕的；可怕的", "ˈɔːfl"),
    ("backward", "adj. 向后的 adv. 倒", "ˈbækwərd"),
    ("balance", "n. 平衡 v. 使平衡", "ˈbæləns"),
    ("ban", "v./n. 禁止；禁令", "bæn"),
    ("bargain", "n. 便宜货 v. 讨价还价", "ˈbɑːrɡɪn"),
    ("barrier", "n. 障碍；屏障", "ˈbæriər"),
    ("basis", "n. 基础；根据", "ˈbeɪsɪs"),
    ("battle", "n. 战斗 v. 斗争", "ˈbætl"),
    ("bear", "v. 承受；忍受 n. 熊", "beər"),
    ("behalf", "n. 代表；利益", "bɪˈhɑːf"),
    ("behave", "v. 表现；举止", "bɪˈheɪv"),
    ("belief", "n. 信仰；信念", "bɪˈliːf"),
    ("belong", "v. 属于", "bɪˈlɒŋ"),
    ("beneath", "prep. 在…之下", "bɪˈniːθ"),
    ("benefit", "n. 利益 v. 有益于", "ˈbenɪfɪt"),
    ("betray", "v. 背叛；泄露", "bɪˈtreɪ"),
    ("bid", "v./n. 出价；投标", "bɪd"),
    ("blame", "v. 责备 n. 过失", "bleɪm"),
    ("blank", "adj. 空白的 n. 空白", "blæŋk"),
    ("blast", "n. 爆炸 v. 炸毁", "blɑːst"),
    ("blend", "v. 混合 n. 混合物", "blend"),
    ("bloom", "v. 开花 n. 花", "bluːm"),
    ("board", "n. 板；董事会 v. 登上", "bɔːrd"),
    ("boast", "v. 自夸 n. 吹牛", "bəʊst"),
    ("bond", "n. 纽带；债券", "bɒnd"),
    ("boost", "v. 促进；增加", "buːst"),
    ("border", "n. 边界 v. 接壤", "ˈbɔːrdər"),
    ("bore", "v. 使厌烦 n. 令人厌烦的人", "bɔːr"),
    ("bother", "v. 打扰；烦恼", "ˈbɒðər"),
    ("bounce", "v. 弹跳", "baʊns"),
    ("bound", "adj. 必定的 v. 跳跃", "baʊnd"),
    ("boundary", "n. 边界；分界线", "ˈbaʊndəri"),
    ("brake", "n. 刹车 v. 刹车", "breɪk"),
    ("branch", "n. 树枝；分支", "brɑːntʃ"),
    ("brand", "n. 品牌 v. 铭刻", "brænd"),
    ("breach", "n. 违反；缺口", "briːtʃ"),
    ("breed", "v. 繁殖 n. 品种", "briːd"),
    ("brief", "adj. 简短的 v. 摘要", "briːf"),
    ("brilliant", "adj. 杰出的；明亮的", "ˈbrɪlɪənt"),
    ("broadcast", "v./n. 广播；播放", "ˈbrɔːdkɑːst"),
    ("budget", "n. 预算 v. 编预算", "ˈbʌdʒɪt"),
    ("burden", "n. 负担 v. 使负重", "ˈbɜːrdn"),
    ("burst", "v. 爆炸；突然发作", "bɜːrst"),
    ("cabinet", "n. 内阁；橱柜", "ˈkæbɪnɪt"),
    ("calculate", "v. 计算；推算", "ˈkælkjuleɪt"),
    ("campaign", "n. 运动；战役", "kæmˈpeɪn"),
    ("cancel", "v. 取消；撤销", "ˈkænsl"),
    ("candidate", "n. 候选人", "ˈkændɪdɪt"),
    ("capable", "adj. 有能力的", "ˈkeɪpəbl"),
    ("capacity", "n. 容量；能力", "kəˈpæsɪti"),
    ("capture", "v. 捕获；夺取", "ˈkæptʃər"),
    ("career", "n. 职业；生涯", "kəˈrɪər"),
    ("casual", "adj. 随便的；偶然的", "ˈkæʒuəl"),
    ("catalog", "n. 目录 v. 编目", "ˈkætəlɒɡ"),
    ("cease", "v. 停止；终止", "siːs"),
    ("celebrate", "v. 庆祝", "ˈselɪbreɪt"),
    ("cement", "n. 水泥 v. 巩固", "sɪˈment"),
    ("challenge", "n./v. 挑战", "ˈtʃælɪndʒ"),
    ("champion", "n. 冠军 v. 捍卫", "ˈtʃæmpɪən"),
    ("channel", "n. 频道；渠道", "ˈtʃænl"),
    ("chapter", "n. 章；回", "ˈtʃæptər"),
    ("characteristic", "adj. 特有的 n. 特征", "ˌkærɪktəˈrɪstɪk"),
    ("charge", "v. 收费；指控 n. 费用", "tʃɑːrdʒ"),
    ("charity", "n. 慈善；施舍", "ˈtʃærɪti"),
    ("charm", "n. 魅力 v. 迷住", "tʃɑːrm"),
    ("chase", "v./n. 追逐", "tʃeɪs"),
    ("cheat", "v. 欺骗 n. 骗子", "tʃiːt"),
    ("chief", "adj. 主要的 n. 首领", "tʃiːf"),
    ("chill", "v. 使变冷 n. 寒冷", "tʃɪl"),
    ("chunk", "n. 大块；大量", "tʃʌŋk"),
    ("circumstance", "n. 环境；情况", "ˈsɜːrkəmstæns"),
    ("cite", "v. 引用；引证", "saɪt"),
    ("civil", "adj. 公民的；民事的", "ˈsɪvl"),
    ("claim", "v. 声称；要求 n. 主张", "kleɪm"),
    ("clash", "v. 冲突 n. 冲突", "klæʃ"),
    ("classify", "v. 分类；归类", "ˈklæsɪfaɪ"),
    ("client", "n. 客户；委托人", "ˈklaɪənt"),
    ("climate", "n. 气候", "ˈklaɪmɪt"),
    ("cling", "v. 紧握；依恋", "klɪŋ"),
    ("clue", "n. 线索；提示", "kluː"),
    ("coach", "n. 教练 v. 训练", "kəʊtʃ"),
    ("coalition", "n. 联盟；联合", "ˌkəʊəˈlɪʃn"),
    ("collapse", "v./n. 倒塌；崩溃", "kəˈlæps"),
    ("colleague", "n. 同事", "ˈkɒliːɡ"),
    ("combine", "v. 结合；联合", "kəmˈbaɪn"),
    ("comfort", "n. 舒适 v. 安慰", "ˈkʌmfərt"),
    ("command", "v./n. 命令；指挥", "kəˈmɑːnd"),
    ("comment", "n./v. 评论；意见", "ˈkɒment"),
    ("commerce", "n. 商业；贸易", "ˈkɒmɜːrs"),
    ("commit", "v. 犯(罪)；承诺", "kəˈmɪt"),
    ("communicate", "v. 交流；传达", "kəˈmjuːnɪkeɪt"),
    ("community", "n. 社区；团体", "kəˈmjuːnɪti"),
    ("companion", "n. 同伴；伙伴", "kəmˈpænjən"),
    ("compare", "v. 比较；对比", "kəmˈpeər"),
    ("compel", "v. 强迫；迫使", "kəmˈpel"),
    ("compensate", "v. 补偿；赔偿", "ˈkɒmpenseɪt"),
    ("compete", "v. 竞争；比赛", "kəmˈpiːt"),
    ("complaint", "n. 投诉；抱怨", "kəmˈpleɪnt"),
    ("complex", "adj. 复杂的 n. 综合体", "ˈkɒmpleks"),
    ("comply", "v. 遵从；服从", "kəmˈplaɪ"),
    ("component", "n. 组成部分；元件", "kəmˈpəʊnənt"),
    ("compose", "v. 组成；创作", "kəmˈpəʊz"),
    ("comprehensive", "adj. 全面的；综合的", "ˌkɒmprɪˈhensɪv"),
    ("compromise", "n./v. 妥协；折中", "ˈkɒmprəmaɪz"),
    ("conceive", "v. 构想；怀孕", "kənˈsiːv"),
    ("concentrate", "v. 集中；专心", "ˈkɒnsntreɪt"),
    ("concept", "n. 概念；观念", "ˈkɒnsept"),
    ("concern", "v. 涉及；使担忧 n. 关心", "kənˈsɜːrn"),
    ("conclude", "v. 结束；得出结论", "kənˈkluːd"),
    ("concrete", "adj. 具体的 n. 混凝土", "ˈkɒŋkriːt"),
    ("conduct", "v. 指挥；进行 n. 行为", "ˈkɒndʌkt"),
    ("confess", "v. 坦白；承认", "kənˈfes"),
    ("confidence", "n. 信心；信任", "ˈkɒnfɪdəns"),
    ("confine", "v. 限制；禁闭", "kənˈfaɪn"),
    ("confirm", "v. 证实；确认", "kənˈfɜːrm"),
    ("conflict", "n. 冲突 v. 冲突", "ˈkɒnflɪkt"),
    ("confront", "v. 面对；对抗", "kənˈfrʌnt"),
    ("confuse", "v. 使困惑；混淆", "kənˈfjuːz"),
    ("connect", "v. 连接；联系", "kənˈnekt"),
    ("conscience", "n. 良心；道德感", "ˈkɒnʃəns"),
    ("conscious", "adj. 有意识的；自觉的", "ˈkɒnʃəs"),
    ("consequence", "n. 结果；后果", "ˈkɒnsɪkwəns"),
    ("conserve", "v. 保存；节约", "kənˈsɜːrv"),
    ("consider", "v. 考虑；认为", "kənˈsɪdər"),
    ("consist", "v. 由…组成；在于", "kənˈsɪst"),
    ("constant", "adj. 不断的；恒定的", "ˈkɒnstənt"),
    ("constitute", "v. 构成；组成", "ˈkɒnstɪtjuːt"),
    ("construct", "v. 建造；构建", "kənˈstrʌkt"),
    ("consult", "v. 咨询；查阅", "kənˈsʌlt"),
    ("consume", "v. 消费；消耗", "kənˈsjuːm"),
    ("contact", "n./v. 接触；联系", "ˈkɒntækt"),
    ("contain", "v. 包含；容纳", "kənˈteɪn"),
    ("contemporary", "adj. 当代的 n. 同代人", "kənˈtempəreri"),
    ("content", "n. 内容 adj. 满足的", "ˈkɒntent"),
    ("contest", "n. 竞赛 v. 争夺", "ˈkɒntest"),
    ("context", "n. 上下文；背景", "ˈkɒntekst"),
    ("contract", "n. 合同 v. 收缩", "ˈkɒntrækt"),
    ("contradict", "v. 反驳；与…矛盾", "ˌkɒntrəˈdɪkt"),
    ("contribute", "v. 贡献；捐助", "kənˈtrɪbjuːt"),
    ("controversial", "adj. 有争议的", "ˌkɒntrəˈvɜːrʃl"),
    ("convenience", "n. 方便；便利", "kənˈviːniəns"),
    ("convention", "n. 惯例；大会", "kənˈvenʃn"),
    ("convert", "v. 转变；转换", "kənˈvɜːrt"),
    ("convey", "v. 传达；运送", "kənˈveɪ"),
    ("convince", "v. 使确信；说服", "kənˈvɪns"),
    ("cooperate", "v. 合作；协作", "kəʊˈɒpəreɪt"),
    ("cope", "v. 应付；处理", "kəʊp"),
    ("core", "n. 核心；要点", "kɔːr"),
    ("corporate", "adj. 公司的；法人的", "ˈkɔːrpərɪt"),
    ("correct", "adj. 正确的 v. 纠正", "kəˈrekt"),
    ("correspond", "v. 符合；通信", "ˌkɒrɪˈspɒnd"),
    ("corrupt", "adj. 腐败的 v. 使堕落", "kəˈrʌpt"),
    ("costume", "n. 服装；戏装", "ˈkɒstjuːm"),
    ("council", "n. 委员会；理事会", "ˈkaʊnsl"),
    ("counter", "n. 柜台 v. 对抗", "ˈkaʊntər"),
    ("courage", "n. 勇气；胆量", "ˈkʌrɪdʒ"),
    ("crash", "v./n. 碰撞；坠毁", "kræʃ"),
    ("creative", "adj. 创造性的", "kriˈeɪtɪv"),
    ("credit", "n. 信用；学分 v. 归功于", "ˈkredɪt"),
    ("crime", "n. 罪行；犯罪", "kraɪm"),
    ("crisis", "n. 危机", "ˈkraɪsɪs"),
    ("criterion", "n. 标准；准则", "kraɪˈtɪəriən"),
    ("critical", "adj. 批评的；关键的", "ˈkrɪtɪkl"),
    ("crucial", "adj. 至关重要的", "ˈkruːʃl"),
    ("crush", "v. 压碎；镇压", "krʌʃ"),
    ("crystal", "n. 水晶 adj. 清澈的", "ˈkrɪstl"),
    ("cultivate", "v. 培养；耕作", "ˈkʌltɪveɪt"),
    ("culture", "n. 文化；修养", "ˈkʌltʃər"),
    ("curiosity", "n. 好奇心", "ˌkjʊəriˈɒsɪti"),
    ("curse", "n./v. 诅咒", "kɜːrs"),
    ("curve", "n. 曲线 v. 弯曲", "kɜːrv"),
    ("cycle", "n. 循环 v. 骑车", "ˈsaɪkl"),
    ("deadline", "n. 截止日期", "ˈdedlaɪn"),
    ("debate", "n./v. 辩论；争论", "dɪˈbeɪt"),
    ("decade", "n. 十年", "ˈdekeɪd"),
    ("decay", "v./n. 腐烂；衰退", "dɪˈkeɪ"),
    ("deceive", "v. 欺骗；蒙蔽", "dɪˈsiːv"),
    ("declare", "v. 宣布；声明", "dɪˈkleər"),
    ("decline", "v. 下降；拒绝 n. 下降", "dɪˈklaɪn"),
    ("decorate", "v. 装饰；装修", "ˈdekəreɪt"),
    ("decrease", "v./n. 减少", "dɪˈkriːs"),
    ("dedicate", "v. 奉献；致力于", "ˈdedɪkeɪt"),
    ("defeat", "v./n. 击败；失败", "dɪˈfiːt"),
    ("defend", "v. 防御；辩护", "dɪˈfend"),
    ("define", "v. 定义；限定", "dɪˈfaɪn"),
    ("definite", "adj. 明确的；确定的", "ˈdefɪnɪt"),
    ("defy", "v. 违抗；蔑视", "dɪˈfaɪ"),
    ("delay", "v./n. 延迟；耽搁", "dɪˈleɪ"),
    ("delegate", "n. 代表 v. 委派", "ˈdelɪɡeɪt"),
    ("deliberate", "adj. 故意的 v. 仔细考虑", "dɪˈlɪbərɪt"),
    ("delicate", "adj. 精美的；脆弱的", "ˈdelɪkɪt"),
    ("deliver", "v. 递送；发表", "dɪˈlɪvər"),
    ("demand", "v./n. 要求；需求", "dɪˈmɑːnd"),
    ("democracy", "n. 民主；民主制度", "dɪˈmɒkrəsi"),
    ("demonstrate", "v. 证明；示范", "ˈdemənstreɪt"),
    ("deny", "v. 否认；拒绝", "dɪˈnaɪ"),
    ("depart", "v. 离开；出发", "dɪˈpɑːrt"),
    ("depend", "v. 依靠；取决于", "dɪˈpend"),
    ("deposit", "n. 存款；押金 v. 存放", "dɪˈpɒzɪt"),
    ("depress", "v. 使沮丧；压下", "dɪˈpres"),
    ("derive", "v. 起源于；获得", "dɪˈraɪv"),
    ("describe", "v. 描述；描写", "dɪˈskraɪb"),
    ("deserve", "v. 应得；值得", "dɪˈzɜːrv"),
    ("design", "n./v. 设计", "dɪˈzaɪn"),
    ("desire", "n./v. 渴望；欲望", "dɪˈzaɪər"),
    ("despair", "n./v. 绝望", "dɪˈspeər"),
    ("destination", "n. 目的地", "ˌdestɪˈneɪʃn"),
    ("destroy", "v. 破坏；毁灭", "dɪˈstrɔɪ"),
    ("detect", "v. 发现；侦测", "dɪˈtekt"),
    ("determine", "v. 决定；确定", "dɪˈtɜːrmɪn"),
    ("device", "n. 设备；装置", "dɪˈvaɪs"),
    ("devote", "v. 奉献；致力于", "dɪˈvəʊt"),
    ("diagnose", "v. 诊断", "ˈdaɪəɡnəʊz"),
    ("dialect", "n. 方言", "ˈdaɪəlekt"),
    ("differ", "v. 不同；相异", "ˈdɪfər"),
    ("digest", "v. 消化；摘要", "daɪˈdʒest"),
    ("dilemma", "n. 困境；进退两难", "dɪˈlemə"),
    ("dimension", "n. 尺寸；维度", "daɪˈmenʃn"),
    ("diminish", "v. 减少；缩小", "dɪˈmɪnɪʃ"),
    ("diploma", "n. 文凭；毕业证书", "dɪˈpləʊmə"),
    ("direct", "adj. 直接的 v. 指导", "dɪˈrekt"),
    ("discipline", "n. 纪律；学科 v. 训练", "ˈdɪsɪplɪn"),
    ("discount", "n. 折扣 v. 打折", "ˈdɪskaʊnt"),
    ("discover", "v. 发现", "dɪˈskʌvər"),
    ("disguise", "v./n. 伪装；假扮", "dɪsˈɡaɪz"),
    ("dismiss", "v. 解雇；驳回", "dɪsˈmɪs"),
    ("display", "v./n. 展示；陈列", "dɪˈspleɪ"),
    ("dispose", "v. 处理；安排", "dɪˈspəʊz"),
    ("dispute", "n./v. 争论；纠纷", "dɪˈspjuːt"),
    ("disrupt", "v. 扰乱；破坏", "dɪsˈrʌpt"),
    ("dissolve", "v. 溶解；解散", "dɪˈzɒlv"),
    ("distance", "n. 距离；远方", "ˈdɪstəns"),
    ("distinct", "adj. 明显的；独特的", "dɪˈstɪŋkt"),
    ("distinguish", "v. 区别；辨认", "dɪˈstɪŋɡwɪʃ"),
    ("distribute", "v. 分配；分发", "dɪˈstrɪbjuːt"),
    ("disturb", "v. 打扰；扰乱", "dɪˈstɜːrb"),
    ("diverse", "adj. 多样的；不同的", "daɪˈvɜːrs"),
    ("domestic", "adj. 国内的；家庭的", "dəˈmestɪk"),
    ("dominate", "v. 支配；统治", "ˈdɒmɪneɪt"),
    ("donate", "v. 捐赠", "dəʊˈneɪt"),
    ("draft", "n. 草稿 v. 起草", "drɑːft"),
    ("drain", "v. 排水 n. 下水道", "dreɪn"),
    ("dramatic", "adj. 戏剧性的；引人注目的", "drəˈmætɪk"),
    ("durable", "adj. 耐用的；持久的", "ˈdjʊərəbl"),
    ("dynamic", "adj. 动态的；有活力的", "daɪˈnæmɪk"),
    ("eager", "adj. 渴望的；热切的", "ˈiːɡər"),
    ("earn", "v. 赚得；获得", "ɜːrn"),
    ("ease", "n. 容易 v. 缓解", "iːz"),
    ("echo", "n. 回声 v. 回响", "ˈekəʊ"),
    ("ecology", "n. 生态学", "iˈkɒlədʒi"),
    ("economy", "n. 经济；节约", "ɪˈkɒnəmi"),
    ("edge", "n. 边缘；优势", "edʒ"),
    ("edition", "n. 版本；版次", "ɪˈdɪʃn"),
    ("effective", "adj. 有效的", "ɪˈfektɪv"),
    ("efficient", "adj. 高效的", "ɪˈfɪʃnt"),
    ("elaborate", "adj. 精心的 v. 详述", "ɪˈlæbərɪt"),
    ("elect", "v. 选举；推选", "ɪˈlekt"),
    ("elegant", "adj. 优雅的；精美的", "ˈelɪɡənt"),
    ("element", "n. 元素；要素", "ˈelɪmənt"),
    ("eliminate", "v. 消除；淘汰", "ɪˈlɪmɪneɪt"),
    ("embrace", "v. 拥抱；接受", "ɪmˈbreɪs"),
    ("emerge", "v. 出现；浮现", "ɪmˈmɜːrdʒ"),
    ("emotion", "n. 情感；情绪", "ɪˈməʊʃn"),
    ("emphasize", "v. 强调；着重", "ˈemfəsaɪz"),
    ("employ", "v. 雇用；使用", "ɪmˈplɔɪ"),
    ("enable", "v. 使能够", "ɪˈneɪbl"),
    ("encounter", "v./n. 遭遇；邂逅", "ɪnˈkaʊntər"),
    ("encourage", "v. 鼓励；支持", "ɪnˈkʌrɪdʒ"),
    ("endure", "v. 忍受；持久", "ɪnˈdjʊər"),
    ("enforce", "v. 执行；强制", "ɪnˈfɔːrs"),
    ("engage", "v. 参与；从事", "ɪnˈɡeɪdʒ"),
    ("enhance", "v. 增强；提高", "ɪnˈhɑːns"),
    ("enormous", "adj. 巨大的", "ɪˈnɔːrməs"),
    ("ensure", "v. 确保；保证", "ɪnˈʃʊər"),
    ("enterprise", "n. 企业；事业", "ˈentərpraɪz"),
    ("enthusiasm", "n. 热情；热忱", "ɪnˈθjuːziæzəm"),
    ("entire", "adj. 全部的；整个的", "ɪnˈtaɪər"),
    ("entry", "n. 进入；入口", "ˈentri"),
    ("environment", "n. 环境", "ɪnˈvaɪrənmənt"),
    ("episode", "n. 一集；事件", "ˈepɪsəʊd"),
    ("equal", "adj. 相等的 v. 等于", "ˈiːkwəl"),
    ("equip", "v. 装备；配备", "ɪˈkwɪp"),
    ("equivalent", "adj. 等价的 n. 等价物", "ɪˈkwɪvələnt"),
    ("era", "n. 时代；纪元", "ˈɪərə"),
    ("error", "n. 错误；误差", "ˈerər"),
    ("essential", "adj. 必要的；本质的", "ɪˈsenʃl"),
    ("establish", "v. 建立；确立", "ɪˈstæblɪʃ"),
    ("estate", "n. 房地产；财产", "ɪˈsteɪt"),
    ("estimate", "v./n. 估计；估价", "ˈestɪmeɪt"),
    ("evaluate", "v. 评估；评价", "ɪˈvæljueɪt"),
    ("evidence", "n. 证据；迹象", "ˈevɪdəns"),
    ("evident", "adj. 明显的", "ˈevɪdənt"),
    ("evil", "adj. 邪恶的 n. 邪恶", "ˈiːvl"),
    ("evolve", "v. 进化；发展", "ɪˈvɒlv"),
    ("exaggerate", "v. 夸大；夸张", "ɪɡˈzædʒəreɪt"),
    ("examine", "v. 检查；审查", "ɪɡˈzæmɪn"),
    ("exceed", "v. 超过；超越", "ɪkˈsiːd"),
    ("exception", "n. 例外", "ɪkˈsepʃn"),
    ("excess", "n. 过量 adj. 过量的", "ɪkˈses"),
    ("exchange", "v./n. 交换；兑换", "ɪksˈtʃeɪndʒ"),
    ("exclude", "v. 排除；排斥", "ɪkˈskluːd"),
    ("execute", "v. 执行；处决", "ˈeksɪkjuːt"),
    ("exhibit", "v. 展览 n. 展品", "ɪɡˈzɪbɪt"),
    ("exist", "v. 存在", "ɪɡˈzɪst"),
    ("expand", "v. 扩大；扩展", "ɪkˈspænd"),
    ("expedition", "n. 远征；探险", "ˌekspɪˈdɪʃn"),
    ("expense", "n. 花费；费用", "ɪkˈspens"),
    ("experimental", "adj. 实验性的", "ɪkˌsperɪˈmentl"),
    ("expert", "n. 专家 adj. 熟练的", "ˈekspɜːrt"),
    ("exploit", "v. 利用；剥削", "ɪkˈsplɔɪt"),
    ("explore", "v. 探索；探究", "ɪkˈsplɔːr"),
    ("explosive", "adj. 爆炸性的 n. 炸药", "ɪkˈspləʊsɪv"),
    ("expose", "v. 暴露；揭露", "ɪkˈspəʊz"),
    ("extend", "v. 延伸；扩展", "ɪkˈstend"),
    ("extent", "n. 程度；范围", "ɪkˈstent"),
    ("exterior", "adj. 外部的 n. 外部", "ɪkˈstɪəriər"),
    ("external", "adj. 外部的；外面的", "ɪkˈstɜːrnl"),
    ("extraordinary", "adj. 非凡的；特别的", "ɪkˈstrɔːrdnri"),
    ("extreme", "adj. 极端的 n. 极端", "ɪkˈstriːm"),
    ("facility", "n. 设施；设备", "fəˈsɪlɪti"),
    ("factor", "n. 因素；要素", "ˈfæktər"),
    ("faculty", "n. 才能；全体教员", "ˈfæklti"),
    ("failure", "n. 失败；故障", "ˈfeɪljər"),
    ("faith", "n. 信仰；信任", "feɪθ"),
    ("familiar", "adj. 熟悉的", "fəˈmɪliər"),
    ("fancy", "adj. 精致的 v. 想象", "ˈfænsi"),
    ("fantastic", "adj. 极好的；奇异的", "fænˈtæstɪk"),
    ("fascinate", "v. 迷住；使着迷", "ˈfæsɪneɪt"),
    ("fatal", "adj. 致命的", "ˈfeɪtl"),
    ("fatigue", "n. 疲劳 v. 使疲劳", "fəˈtiːɡ"),
    ("fault", "n. 错误；缺点", "fɔːlt"),
    ("favor", "n. 好感 v. 赞成", "ˈfeɪvər"),
    ("feature", "n. 特征；特色", "ˈfiːtʃər"),
    ("federal", "adj. 联邦的", "ˈfedərəl"),
    ("fiction", "n. 小说；虚构", "ˈfɪkʃn"),
    ("figure", "n. 数字；人物 v. 计算", "ˈfɪɡər"),
    ("finance", "n. 财政；金融 v. 资助", "ˈfaɪnæns"),
    ("flexible", "adj. 灵活的；柔韧的", "ˈfleksəbl"),
    ("flight", "n. 航班；飞行", "flaɪt"),
    ("fluent", "adj. 流利的", "ˈfluːənt"),
    ("focus", "v. 集中 n. 焦点", "ˈfəʊkəs"),
    ("forbid", "v. 禁止", "fərˈbɪd"),
    ("forecast", "v./n. 预测；预报", "ˈfɔːrkɑːst"),
    ("forge", "v. 锻造；伪造", "fɔːrdʒ"),
    ("format", "n. 格式 v. 格式化", "ˈfɔːrmæt"),
    ("formula", "n. 公式；配方", "ˈfɔːrmjələ"),
    ("fortune", "n. 运气；财富", "ˈfɔːrtʃuːn"),
    ("foundation", "n. 基础；基金会", "faʊnˈdeɪʃn"),
    ("fraction", "n. 分数；小部分", "ˈfrækʃn"),
    ("fragment", "n. 碎片；片段", "ˈfræɡmənt"),
    ("frame", "n. 框架 v. 设计", "freɪm"),
    ("framework", "n. 框架；体制", "ˈfreɪmwɜːrk"),
    ("frank", "adj. 坦白的；直率的", "fræŋk"),
    ("fraud", "n. 欺诈；骗子", "frɔːd"),
    ("frequency", "n. 频率；频繁", "ˈfriːkwənsi"),
    ("frontier", "n. 边境；前沿", "ˈfrʌntɪər"),
    ("frustrate", "v. 使沮丧；挫败", "frʌˈstreɪt"),
    ("fulfill", "v. 实现；履行", "fʊlˈfɪl"),
    ("function", "n. 功能 v. 运行", "ˈfʌŋkʃn"),
    ("fund", "n. 基金 v. 资助", "fʌnd"),
    ("fundamental", "adj. 基本的；根本的", "ˌfʌndəˈmentl"),
    ("furnish", "v. 装备；提供", "ˈfɜːrnɪʃ"),
    ("galaxy", "n. 银河；星系", "ˈɡæləksi"),
    ("gallery", "n. 画廊；走廊", "ˈɡæləri"),
    ("gap", "n. 缺口；差距", "ɡæp"),
    ("garlic", "n. 大蒜", "ˈɡɑːrlɪk"),
    ("gather", "v. 集合；收集", "ˈɡæðər"),
    ("gaze", "v./n. 凝视", "ɡeɪz"),
    ("gender", "n. 性别", "ˈdʒendər"),
    ("generate", "v. 产生；发生", "ˈdʒenəreɪt"),
    ("generous", "adj. 慷慨的；大方的", "ˈdʒenərəs"),
    ("genius", "n. 天才；天赋", "ˈdʒiːnɪəs"),
    ("genuine", "adj. 真正的；真诚的", "ˈdʒenjuɪn"),
    ("gesture", "n. 手势 v. 做手势", "ˈdʒestʃər"),
    ("globe", "n. 地球；球体", "ɡləʊb"),
    ("glorious", "adj. 光荣的；壮丽的", "ˈɡlɔːriəs"),
    ("govern", "v. 统治；管理", "ˈɡʌvərn"),
    ("grace", "n. 优雅；恩惠", "ɡreɪs"),
    ("gradual", "adj. 逐渐的", "ˈɡrædʒuəl"),
    ("grant", "v. 授予 n. 拨款", "ɡrɑːnt"),
    ("grasp", "v. 抓住；理解", "ɡrɑːsp"),
    ("grateful", "adj. 感激的", "ˈɡreɪtfl"),
    ("gravity", "n. 重力；严重性", "ˈɡrævɪti"),
    ("guarantee", "v./n. 保证；担保", "ˌɡærənˈtiː"),
    ("guidance", "n. 指导；引导", "ˈɡaɪdəns"),
    ("guilty", "adj. 有罪的；内疚的", "ˈɡɪlti"),
    ("halt", "v./n. 停止；暂停", "hɔːlt"),
    ("hamper", "v. 妨碍；阻碍", "ˈhæmpər"),
    ("handle", "v. 处理 n. 把手", "ˈhændl"),
    ("harbor", "n. 港口 v. 庇护", "ˈhɑːrbər"),
    ("harmony", "n. 和谐；协调", "ˈhɑːrməni"),
    ("harvest", "n./v. 收获；收割", "ˈhɑːrvɪst"),
    ("hatred", "n. 仇恨；憎恨", "ˈheɪtrɪd"),
    ("hazard", "n. 危险 v. 冒险", "ˈhæzərd"),
    ("heading", "n. 标题", "ˈhedɪŋ"),
    ("heal", "v. 治愈；愈合", "hiːl"),
    ("heritage", "n. 遗产；传统", "ˈherɪtɪdʒ"),
    ("hesitate", "v. 犹豫；踌躇", "ˈhezɪteɪt"),
    ("highlight", "v. 强调 n. 亮点", "ˈhaɪlaɪt"),
    ("hinder", "v. 阻碍；妨碍", "ˈhɪndər"),
    ("hint", "n. 暗示 v. 暗示", "hɪnt"),
    ("horizon", "n. 地平线；眼界", "həˈraɪzn"),
    ("horror", "n. 恐怖；厌恶", "ˈhɒrər"),
    ("hostile", "adj. 敌意的；不友好的", "ˈhɒstaɪl"),
    ("humble", "adj. 谦虚的；卑微的", "ˈhʌmbl"),
    ("humor", "n. 幽默；心情", "ˈhjuːmər"),
    ("hunger", "n. 饥饿；渴望", "ˈhʌŋɡər"),
    ("hypothesis", "n. 假设；假说", "haɪˈpɒθəsɪs"),
    ("identical", "adj. 完全相同的", "aɪˈdentɪkl"),
    ("identify", "v. 识别；确认", "aɪˈdentɪfaɪ"),
    ("ideology", "n. 意识形态", "ˌaɪdiˈɒlədʒi"),
    ("ignorance", "n. 无知；愚昧", "ˈɪɡnərəns"),
    ("ignore", "v. 忽视；不理睬", "ɪɡˈnɔːr"),
    ("illustrate", "v. 说明；插图", "ˈɪləstreɪt"),
    ("imaginary", "adj. 想象的；虚构的", "ɪˈmædʒɪnəri"),
    ("immense", "adj. 巨大的；广大的", "ɪˈmens"),
    ("immigrate", "v. 移民", "ˈɪmɪɡreɪt"),
    ("impact", "n./v. 影响；冲击", "ˈɪmpækt"),
    ("implement", "v. 实施 n. 工具", "ˈɪmplɪment"),
    ("implication", "n. 含义；暗示", "ˌɪmplɪˈkeɪʃn"),
    ("impose", "v. 强加；征收", "ɪmˈpəʊz"),
    ("impress", "v. 给…深刻印象", "ɪmˈpres"),
    ("impulse", "n. 冲动；脉冲", "ˈɪmpʌls"),
    ("incident", "n. 事件；事故", "ˈɪnsɪdənt"),
    ("inclined", "adj. 倾向于…的", "ɪnˈklaɪnd"),
    ("include", "v. 包括；包含", "ɪnˈkluːd"),
    ("income", "n. 收入；收益", "ˈɪnkʌm"),
    ("incorporate", "v. 合并；包含", "ɪnˈkɔːrpəreɪt"),
    ("incredible", "adj. 难以置信的", "ɪnˈkredəbl"),
    ("independence", "n. 独立；自主", "ˌɪndɪˈpendəns"),
    ("indicate", "v. 表明；指出", "ˈɪndɪkeɪt"),
    ("individual", "adj. 个人的 n. 个人", "ˌɪndɪˈvɪdʒuəl"),
    ("inevitable", "adj. 不可避免的", "ɪnˈevɪtəbl"),
    ("inflation", "n. 通货膨胀", "ɪnˈfleɪʃn"),
    ("influence", "n./v. 影响", "ˈɪnfluəns"),
    ("infrastructure", "n. 基础设施", "ˈɪnfrəstrʌktʃər"),
    ("inherit", "v. 继承", "ɪnˈherɪt"),
    ("initial", "adj. 最初的 n. 首字母", "ɪˈnɪʃl"),
    ("initiative", "n. 主动性；倡议", "ɪˈnɪʃətɪv"),
    ("innocent", "adj. 无辜的；天真的", "ˈɪnəsnt"),
    ("innovation", "n. 创新；革新", "ˌɪnəˈveɪʃn"),
    ("input", "n. 输入；投入", "ˈɪnpʊt"),
    ("inquire", "v. 询问；调查", "ɪnˈkwaɪər"),
    ("insert", "v. 插入；嵌入", "ɪnˈsɜːrt"),
    ("insight", "n. 洞察力；见识", "ˈɪnsaɪt"),
    ("inspect", "v. 检查；视察", "ɪnˈspekt"),
    ("inspire", "v. 激励；启发", "ɪnˈspaɪər"),
    ("install", "v. 安装；设置", "ɪnˈstɔːl"),
    ("instance", "n. 例子；实例", "ˈɪnstəns"),
    ("instinct", "n. 本能；直觉", "ˈɪnstɪŋkt"),
    ("institute", "n. 学院 v. 制定", "ˈɪnstɪtjuːt"),
    ("instrument", "n. 乐器；工具", "ˈɪnstrəmənt"),
    ("insult", "v./n. 侮辱", "ɪnˈsʌlt"),
    ("insurance", "n. 保险", "ɪnˈʃʊərəns"),
    ("integrate", "v. 整合；融入", "ˈɪntɪɡreɪt"),
    ("intellectual", "adj. 智力的 n. 知识分子", "ˌɪntəˈlektʃuəl"),
    ("intelligence", "n. 智力；情报", "ɪnˈtelɪdʒəns"),
    ("intend", "v. 打算；想要", "ɪnˈtend"),
    ("intense", "adj. 强烈的；紧张的", "ɪnˈtens"),
    ("interact", "v. 互动；交流", "ˌɪntərˈækt"),
    ("interior", "adj. 内部的 n. 内部", "ɪnˈtɪəriər"),
    ("interpret", "v. 解释；口译", "ɪnˈtɜːrprɪt"),
    ("intervene", "v. 干预；介入", "ˌɪntərˈviːn"),
    ("intimate", "adj. 亲密的 n. 知己", "ˈɪntɪmɪt"),
    ("invade", "v. 侵略；入侵", "ɪnˈveɪd"),
    ("investigate", "v. 调查；研究", "ɪnˈvestɪɡeɪt"),
    ("investment", "n. 投资", "ɪnˈvestmənt"),
    ("invisible", "adj. 看不见的", "ɪnˈvɪzəbl"),
    ("involve", "v. 涉及；包含", "ɪnˈvɒlv"),
    ("isolate", "v. 隔离；孤立", "ˈaɪsəleɪt"),
    ("issue", "n. 问题 v. 发布", "ˈɪʃuː"),
    ("joint", "adj. 联合的 n. 关节", "dʒɔɪnt"),
    ("journal", "n. 期刊；日志", "ˈdʒɜːrnl"),
    ("journey", "n. 旅行 v. 旅行", "ˈdʒɜːrni"),
    ("judge", "v. 判断 n. 法官", "dʒʌdʒ"),
    ("judgment", "n. 判断力；审判", "ˈdʒʌdʒmənt"),
    ("junction", "n. 交汇处；连接点", "ˈdʒʌŋkʃn"),
    ("justice", "n. 正义；司法", "ˈdʒʌstɪs"),
    ("justify", "v. 证明…正当；为…辩护", "ˈdʒʌstɪfaɪ"),
    ("kernel", "n. 核心；仁", "ˈkɜːrnl"),
    ("kingdom", "n. 王国；领域", "ˈkɪŋdəm"),
    ("knit", "v. 编织；紧密结合", "nɪt"),
    ("label", "n. 标签 v. 标注", "ˈleɪbl"),
    ("labor", "n. 劳动 v. 劳动", "ˈleɪbər"),
    ("landscape", "n. 风景；地形", "ˈlændskeɪp"),
    ("launch", "v. 发射；发起 n. 发射", "lɔːntʃ"),
    ("layer", "n. 层 v. 分层", "ˈleɪər"),
    ("leadership", "n. 领导力；领导层", "ˈliːdərʃɪp"),
    ("league", "n. 联盟；联赛", "liːɡ"),
    ("lean", "v. 倾斜 adj. 瘦的", "liːn"),
    ("legal", "adj. 法律的；合法的", "ˈliːɡl"),
    ("legend", "n. 传说；传奇", "ˈledʒənd"),
    ("legislation", "n. 法律；立法", "ˌledʒɪsˈleɪʃn"),
    ("legitimate", "adj. 合法的；正当的", "lɪˈdʒɪtɪmɪt"),
    ("leisure", "n. 闲暇；休闲", "ˈleʒər"),
    ("liberal", "adj. 自由的；开明的", "ˈlɪbərəl"),
    ("liberty", "n. 自由；解放", "ˈlɪbərti"),
    ("license", "n. 执照 v. 许可", "ˈlaɪsəns"),
    ("likewise", "adv. 同样地；也", "ˈlaɪkwaɪz"),
    ("limitation", "n. 限制；局限", "ˌlɪmɪˈteɪʃn"),
    ("linger", "v. 逗留；徘徊", "ˈlɪŋɡər"),
    ("literacy", "n. 读写能力", "ˈlɪtərəsi"),
    ("literary", "adj. 文学的", "ˈlɪtərəri"),
    ("literature", "n. 文学；文献", "ˈlɪtrətʃər"),
    ("lobby", "n. 大厅 v. 游说", "ˈlɒbi"),
    ("locate", "v. 定位；位于", "ləʊˈkeɪt"),
    ("logical", "adj. 逻辑的；合理的", "ˈlɒdʒɪkl"),
    ("loyal", "adj. 忠诚的", "ˈlɔɪəl"),
    ("luxury", "n. 奢侈；奢华", "ˈlʌkʃəri"),
    ("magnificent", "adj. 壮丽的；极好的", "mæɡˈnɪfɪsnt"),
    ("maintain", "v. 维持；保养", "meɪnˈteɪn"),
    ("major", "adj. 主要的 n. 专业", "ˈmeɪdʒər"),
    ("manage", "v. 管理；设法", "ˈmænɪdʒ"),
    ("manifest", "adj. 明显的 v. 表明", "ˈmænɪfest"),
    ("manipulate", "v. 操纵；控制", "məˈnɪpjuleɪt"),
    ("manner", "n. 方式；举止", "ˈmænər"),
    ("manual", "adj. 手工的 n. 手册", "ˈmænjuəl"),
    ("manufacture", "v. 制造 n. 制造业", "ˌmænjuˈfæktʃər"),
    ("margin", "n. 边缘；利润", "ˈmɑːrdʒɪn"),
    ("mature", "adj. 成熟的 v. 成熟", "məˈtʃʊər"),
    ("maximum", "n. 最大值 adj. 最大的", "ˈmæksɪməm"),
    ("measure", "v. 测量 n. 措施", "ˈmeʒər"),
    ("mechanism", "n. 机制；机械装置", "ˈmekənɪzəm"),
    ("media", "n. 媒体", "ˈmiːdiə"),
    ("mediate", "v. 调解；斡旋", "ˈmiːdieɪt"),
    ("medicine", "n. 药；医学", "ˈmedɪsn"),
    ("medium", "n. 媒介 adj. 中等的", "ˈmiːdiəm"),
    ("mental", "adj. 精神的；心理的", "ˈmentl"),
    ("mention", "v./n. 提及；说起", "ˈmenʃn"),
    ("merchant", "n. 商人", "ˈmɜːrtʃənt"),
    ("mercy", "n. 仁慈；怜悯", "ˈmɜːrsi"),
    ("merit", "n. 优点 v. 值得", "ˈmerɪt"),
    ("method", "n. 方法；办法", "ˈmeθəd"),
    ("migrate", "v. 迁移；移居", "maɪˈɡreɪt"),
    ("military", "adj. 军事的 n. 军队", "ˈmɪlɪtəri"),
    ("minimum", "n. 最小值 adj. 最小的", "ˈmɪnɪməm"),
    ("minister", "n. 部长；牧师", "ˈmɪnɪstər"),
    ("minor", "adj. 较小的 n. 未成年人", "ˈmaɪnər"),
    ("miracle", "n. 奇迹", "ˈmɪrəkl"),
    ("mission", "n. 任务；使命", "ˈmɪʃn"),
    ("moderate", "adj. 适度的 v. 缓和", "ˈmɒdərɪt"),
    ("modify", "v. 修改；调整", "ˈmɒdɪfaɪ"),
    ("monitor", "v. 监控 n. 显示器", "ˈmɒnɪtər"),
    ("monopoly", "n. 垄断", "məˈnɒpəli"),
    ("moral", "adj. 道德的 n. 寓意", "ˈmɒrəl"),
    ("motion", "n. 运动；动议", "ˈməʊʃn"),
    ("motivate", "v. 激励；激发", "ˈməʊtɪveɪt"),
    ("motive", "n. 动机 adj. 发动的", "ˈməʊtɪv"),
    ("multiply", "v. 增加；繁殖", "ˈmʌltɪplaɪ"),
    ("mutual", "adj. 相互的；共同的", "ˈmjuːtʃuəl"),
    ("mystery", "n. 神秘；谜", "ˈmɪstəri"),
    ("narrate", "v. 叙述；讲述", "nəˈreɪt"),
    ("narrow", "adj. 狭窄的 v. 变窄", "ˈnærəʊ"),
    ("navigate", "v. 导航；航行", "ˈnævɪɡeɪt"),
    ("neglect", "v./n. 忽视；疏忽", "nɪˈɡlekt"),
    ("negotiate", "v. 谈判；协商", "nɪˈɡəʊʃieɪt"),
    ("neutral", "adj. 中立的", "ˈnjuːtrəl"),
    ("nightmare", "n. 噩梦", "ˈnaɪtmeər"),
    ("noble", "adj. 高尚的；贵族的", "ˈnəʊbl"),
    ("nominate", "v. 提名；任命", "ˈnɒmɪneɪt"),
    ("norm", "n. 规范；标准", "nɔːrm"),
    ("notable", "adj. 显著的；著名的", "ˈnəʊtəbl"),
    ("notify", "v. 通知；报告", "ˈnəʊtɪfaɪ"),
    ("notion", "n. 概念；观念", "ˈnəʊʃn"),
    ("nourish", "v. 滋养；培养", "ˈnʌrɪʃ"),
    ("novel", "n. 小说 adj. 新颖的", "ˈnɒvl"),
    ("numerous", "adj. 许多的；大量的", "ˈnjuːmərəs"),
    ("nurture", "v. 培养；养育", "ˈnɜːrtʃər"),
    ("nutrition", "n. 营养", "njuːˈtrɪʃn"),
    ("obey", "v. 服从；遵守", "əʊˈbeɪ"),
    ("object", "n. 物体 v. 反对", "ˈɒbdʒɪkt"),
    ("objective", "adj. 客观的 n. 目标", "əbˈdʒektɪv"),
    ("oblige", "v. 迫使；施恩", "əˈblaɪdʒ"),
    ("observe", "v. 观察；遵守", "əbˈzɜːrv"),
    ("obstacle", "n. 障碍；阻碍", "ˈɒbstəkl"),
    ("obtain", "v. 获得；得到", "əbˈteɪn"),
    ("obvious", "adj. 明显的", "ˈɒbviəs"),
    ("occasion", "n. 场合；时机", "əˈkeɪʒn"),
    ("occupy", "v. 占据；忙于", "ˈɒkjupaɪ"),
    ("occur", "v. 发生；出现", "əˈkɜːr"),
    ("offend", "v. 冒犯；得罪", "əˈfend"),
    ("official", "adj. 官方的 n. 官员", "əˈfɪʃl"),
    ("ongoing", "adj. 进行中的", "ˈɒnɡəʊɪŋ"),
    ("operate", "v. 操作；运营", "ˈɒpəreɪt"),
    ("opinion", "n. 观点；意见", "əˈpɪnjən"),
    ("opponent", "n. 对手；反对者", "əˈpəʊnənt"),
    ("opportunity", "n. 机会", "ˌɒpərˈtjuːnɪti"),
    ("oppose", "v. 反对；对抗", "əˈpəʊz"),
    ("oppress", "v. 压迫；压抑", "əˈpres"),
    ("option", "n. 选择；选项", "ˈɒpʃn"),
    ("orbit", "n. 轨道 v. 绕轨道运行", "ˈɔːrbɪt"),
    ("ordinary", "adj. 普通的；平凡的", "ˈɔːrdnri"),
    ("organ", "n. 器官；机构", "ˈɔːrɡən"),
    ("organize", "v. 组织；安排", "ˈɔːrɡənaɪz"),
    ("origin", "n. 起源；出身", "ˈɒrɪdʒɪn"),
    ("original", "adj. 原始的；独创的", "əˈrɪdʒɪnl"),
    ("outcome", "n. 结果；成果", "ˈaʊtkʌm"),
    ("outline", "n. 大纲 v. 概述", "ˈaʊtlaɪn"),
    ("output", "n. 产量；输出", "ˈaʊtpʊt"),
    ("overcome", "v. 克服；战胜", "ˌəʊvərˈkʌm"),
    ("overlook", "v. 忽视；俯瞰", "ˌəʊvərˈlʊk"),
    ("overwhelm", "v. 压倒；淹没", "ˌəʊvərˈwelm"),
    ("owe", "v. 欠；归功于", "əʊ"),
    ("pace", "n. 步伐；速度", "peɪs"),
    ("panic", "n./v. 恐慌", "ˈpænɪk"),
    ("parallel", "adj. 平行的 n. 平行线", "ˈpærəlel"),
    ("participate", "v. 参与；参加", "pɑːˈtɪsɪpeɪt"),
    ("particular", "adj. 特定的；挑剔的", "pəˈtɪkjələr"),
    ("passion", "n. 热情；激情", "ˈpæʃn"),
    ("passive", "adj. 被动的；消极的", "ˈpæsɪv"),
    ("pattern", "n. 模式；图案", "ˈpætn"),
    ("penalty", "n. 处罚；罚款", "ˈpenəlti"),
    ("perceive", "v. 察觉；理解", "pəˈsiːv"),
    ("permanent", "adj. 永久的；固定的", "ˈpɜːrmənənt"),
    ("permit", "v. 允许 n. 许可证", "pəˈmɪt"),
    ("persist", "v. 坚持；持续", "pəˈsɪst"),
    ("perspective", "n. 观点；视角", "pərˈspektɪv"),
    ("persuade", "v. 说服；劝告", "pərˈsweɪd"),
    ("phenomenon", "n. 现象", "fɪˈnɒmɪnən"),
    ("philosophy", "n. 哲学", "fɪˈlɒsəfi"),
    ("physical", "adj. 身体的；物理的", "ˈfɪzɪkl"),
    ("plot", "n. 情节；阴谋 v. 绘制", "plɒt"),
    ("pollution", "n. 污染", "pəˈluːʃn"),
    ("populate", "v. 居住于；填充", "ˈpɒpjuleɪt"),
    ("portrait", "n. 肖像；描写", "ˈpɔːrtreɪt"),
    ("possess", "v. 拥有；具有", "pəˈzes"),
    ("postpone", "v. 推迟；延期", "pəʊstˈpəʊn"),
    ("potential", "adj. 潜在的 n. 潜力", "pəˈtenʃl"),
    ("poverty", "n. 贫穷；贫乏", "ˈpɒvərti"),
    ("practically", "adv. 几乎；实际上", "ˈpræktɪkli"),
    ("prayer", "n. 祈祷", "preər"),
    ("precious", "adj. 珍贵的；宝贵的", "ˈpreʃəs"),
    ("precise", "adj. 精确的；准确的", "prɪˈsaɪs"),
    ("predict", "v. 预测；预言", "prɪˈdɪkt"),
    ("predominant", "adj. 主要的；占优势的", "prɪˈdɒmɪnənt"),
    ("prejudice", "n. 偏见 v. 使有偏见", "ˈpredʒədɪs"),
    ("preserve", "v. 保存；保护", "prɪˈzɜːrv"),
    ("prevail", "v. 盛行；获胜", "prɪˈveɪl"),
    ("prevent", "v. 预防；阻止", "prɪˈvent"),
    ("previous", "adj. 以前的；先前的", "ˈpriːviəs"),
    ("primary", "adj. 主要的；初级的", "ˈpraɪməri"),
    ("principle", "n. 原则；原理", "ˈprɪnsəpl"),
    ("priority", "n. 优先权；重点", "praɪˈɒrɪti"),
    ("privilege", "n. 特权；优惠", "ˈprɪvəlɪdʒ"),
    ("proceed", "v. 继续进行", "prəˈsiːd"),
    ("process", "n. 过程 v. 处理", "ˈprəʊses"),
    ("profession", "n. 职业；专业", "prəˈfeʃn"),
    ("profile", "n. 侧面；简介", "ˈprəʊfaɪl"),
    ("profit", "n. 利润 v. 获利", "ˈprɒfɪt"),
    ("prohibit", "v. 禁止；阻止", "prəˈhɪbɪt"),
    ("project", "n. 项目 v. 规划", "ˈprɒdʒekt"),
    ("promote", "v. 促进；晋升", "prəˈməʊt"),
    ("prompt", "adj. 迅速的 v. 促使", "prɒmpt"),
    ("proportion", "n. 比例；部分", "prəˈpɔːʃn"),
    ("propose", "v. 提议；求婚", "prəˈpəʊz"),
    ("prospect", "n. 前景；景色", "ˈprɒspekt"),
    ("prosper", "v. 繁荣；兴旺", "ˈprɒspər"),
    ("protect", "v. 保护；防护", "prəˈtekt"),
    ("protest", "v./n. 抗议；反对", "ˈprəʊtest"),
    ("provoke", "v. 激怒；引起", "prəˈvəʊk"),
    ("publish", "v. 出版；发表", "ˈpʌblɪʃ"),
    ("purchase", "v./n. 购买", "ˈpɜːrtʃəs"),
    ("pursue", "v. 追求；追赶", "pəˈsjuː"),
    ("qualify", "v. 使合格；限定", "ˈkwɒlɪfaɪ"),
    ("quantity", "n. 数量", "ˈkwɒntɪti"),
    ("quest", "n. 探索；追求", "kwest"),
    ("quote", "v. 引用 n. 引文", "kwəʊt"),
    ("radical", "adj. 根本的；激进的", "ˈrædɪkl"),
    ("random", "adj. 随机的 n. 随机", "ˈrændəm"),
    ("range", "n. 范围 v. 变化", "reɪndʒ"),
    ("rank", "n. 等级 v. 排列", "ræŋk"),
    ("rapid", "adj. 迅速的", "ˈræpɪd"),
    ("rare", "adj. 稀有的；罕见的", "reər"),
    ("ratio", "n. 比率；比例", "ˈreɪʃiəʊ"),
    ("rational", "adj. 理性的；合理的", "ˈræʃənl"),
    ("react", "v. 反应；回应", "riˈækt"),
    ("realistic", "adj. 现实的；逼真的", "ˌriːəˈlɪstɪk"),
    ("realm", "n. 领域；王国", "relm"),
    ("rebel", "v. 造反 n. 叛逆者", "rɪˈbel"),
    ("recall", "v. 回忆；召回", "rɪˈkɔːl"),
    ("receipt", "n. 收据；收到", "rɪˈsiːt"),
    ("recession", "n. 衰退；不景气", "rɪˈseʃn"),
    ("recognize", "v. 认出；承认", "ˈrekəɡnaɪz"),
    ("recommend", "v. 推荐；建议", "ˌrekəˈmend"),
    ("recover", "v. 恢复；收回", "rɪˈkʌvər"),
    ("recruit", "v. 招募 n. 新兵", "rɪˈkruːt"),
    ("reduce", "v. 减少；降低", "rɪˈdjuːs"),
    ("refer", "v. 提到；参考", "rɪˈfɜːr"),
    ("refine", "v. 精炼；改进", "rɪˈfaɪn"),
    ("reflect", "v. 反射；反映", "rɪˈflekt"),
    ("reform", "v./n. 改革；改良", "rɪˈfɔːrm"),
    ("refresh", "v. 使恢复；刷新", "rɪˈfreʃ"),
    ("refugee", "n. 难民", "ˌrefjəˈdʒiː"),
    ("refuse", "v. 拒绝", "rɪˈfjuːz"),
    ("regard", "v. 看待 n. 尊重", "rɪˈɡɑːrd"),
    ("region", "n. 地区；区域", "ˈriːdʒən"),
    ("register", "v. 注册；登记", "ˈredʒɪstər"),
    ("regulate", "v. 管理；调节", "ˈreɡjuleɪt"),
    ("reinforce", "v. 加强；增援", "ˌriːɪnˈfɔːrs"),
    ("reject", "v. 拒绝；驳回", "rɪˈdʒekt"),
    ("relate", "v. 联系；叙述", "rɪˈleɪt"),
    ("relative", "adj. 相对的 n. 亲戚", "ˈrelətɪv"),
    ("release", "v./n. 释放；发布", "rɪˈliːs"),
    ("relevant", "adj. 相关的；有关的", "ˈrelɪvənt"),
    ("reliable", "adj. 可靠的", "rɪˈlaɪəbl"),
    ("relief", "n. 减轻；救济", "rɪˈliːf"),
    ("religion", "n. 宗教；信仰", "rɪˈlɪdʒən"),
    ("reluctant", "adj. 不情愿的", "rɪˈlʌktənt"),
    ("rely", "v. 依靠；信赖", "rɪˈlaɪ"),
    ("remain", "v. 保持；剩下", "rɪˈmeɪn"),
    ("remark", "v./n. 评论；言辞", "rɪˈmɑːrk"),
    ("remedy", "n. 补救办法 v. 纠正", "ˈremədi"),
    ("remote", "adj. 遥远的；偏僻的", "rɪˈməʊt"),
    ("render", "v. 使得；给予", "ˈrendər"),
    ("renew", "v. 更新；续期", "rɪˈnjuː"),
    ("rent", "n. 租金 v. 租用", "rent"),
    ("repair", "v./n. 修理；修补", "rɪˈpeər"),
    ("repeat", "v. 重复 n. 重复", "rɪˈpiːt"),
    ("represent", "v. 代表；表示", "ˌreprɪˈzent"),
    ("reproduce", "v. 繁殖；复制", "ˌriːprəˈdjuːs"),
    ("republic", "n. 共和国", "rɪˈpʌblɪk"),
    ("reputation", "n. 名声；声望", "ˌrepjuˈteɪʃn"),
    ("request", "v./n. 请求；要求", "rɪˈkwest"),
    ("require", "v. 需要；要求", "rɪˈkwaɪər"),
    ("rescue", "v./n. 营救；拯救", "ˈreskjuː"),
    ("resemble", "v. 类似；像", "rɪˈzembl"),
    ("reserve", "v. 保留；预定 n. 储备", "rɪˈzɜːrv"),
    ("resident", "n. 居民 adj. 居住的", "ˈrezɪdənt"),
    ("resign", "v. 辞职；放弃", "rɪˈzaɪn"),
    ("resist", "v. 抵抗；抵制", "rɪˈzɪst"),
    ("resolve", "v. 解决；决心", "rɪˈzɒlv"),
    ("resort", "v. 求助 n. 度假胜地", "rɪˈzɔːrt"),
    ("resource", "n. 资源", "rɪˈsɔːrs"),
    ("respond", "v. 回应；反应", "rɪˈspɒnd"),
    ("restore", "v. 恢复；修复", "rɪˈstɔːr"),
    ("restrict", "v. 限制；约束", "rɪˈstrɪkt"),
    ("retain", "v. 保留；保持", "rɪˈteɪn"),
    ("retire", "v. 退休；撤退", "rɪˈtaɪər"),
    ("reveal", "v. 揭示；透露", "rɪˈviːl"),
    ("revenue", "n. 收入；税收", "ˈrevənjuː"),
    ("reverse", "v. 颠倒 adj. 相反的", "rɪˈvɜːrs"),
    ("revise", "v. 修订；复习", "rɪˈvaɪz"),
    ("revive", "v. 复苏；恢复", "rɪˈvaɪv"),
    ("revolt", "v./n. 反叛；起义", "rɪˈvəʊlt"),
    ("reward", "n. 报酬 v. 奖赏", "rɪˈwɔːrd"),
    ("rhythm", "n. 节奏；韵律", "ˈrɪðəm"),
    ("rigid", "adj. 僵硬的；严格的", "ˈrɪdʒɪd"),
    ("risk", "n. 风险 v. 冒险", "rɪsk"),
    ("rival", "n. 对手 adj. 竞争的", "ˈraɪvl"),
    ("role", "n. 角色；作用", "rəʊl"),
    ("routine", "n. 常规 adj. 日常的", "ruːˈtiːn"),
    ("royal", "adj. 皇家的；王室的", "ˈrɔɪəl"),
    ("ruin", "v./n. 毁灭；废墟", "ˈruːɪn"),
    ("rural", "adj. 农村的", "ˈrʊərəl"),
    ("sacrifice", "v./n. 牺牲；献祭", "ˈsækrɪfaɪs"),
    ("salary", "n. 薪水", "ˈsæləri"),
    ("sample", "n. 样品 v. 抽样", "ˈsɑːmpl"),
    ("satisfy", "v. 满足；使满意", "ˈsætɪsfaɪ"),
    ("scale", "n. 规模；比例尺", "skeɪl"),
    ("scan", "v. 扫描；浏览", "skæn"),
    ("scandal", "n. 丑闻", "ˈskændl"),
    ("scarce", "adj. 稀缺的；不足的", "skeərs"),
    ("scatter", "v. 散开；撒播", "ˈskætər"),
    ("scene", "n. 场景；景色", "siːn"),
    ("schedule", "n. 时间表 v. 安排", "ˈʃedjuːl"),
    ("scheme", "n. 计划；方案", "skiːm"),
    ("scholar", "n. 学者", "ˈskɒlər"),
    ("scope", "n. 范围；余地", "skəʊp"),
    ("scratch", "v. 抓；划 n. 划痕", "skrætʃ"),
    ("screen", "n. 屏幕 v. 筛选", "skriːn"),
    ("secure", "adj. 安全的 v. 获得", "sɪˈkjʊər"),
    ("seek", "v. 寻找；寻求", "siːk"),
    ("segment", "n. 部分；段", "ˈseɡmənt"),
    ("seize", "v. 抓住；夺取", "siːz"),
    ("select", "v. 选择 adj. 精选的", "sɪˈlekt"),
    ("senior", "adj. 高级的 n. 长辈", "ˈsiːnɪər"),
    ("sensation", "n. 感觉；轰动", "senˈseɪʃn"),
    ("sense", "n. 感觉；意义 v. 感知", "sens"),
    ("sequence", "n. 顺序；序列", "ˈsiːkwəns"),
    ("session", "n. 会议；一段时间", "ˈseʃn"),
    ("settle", "v. 解决；定居", "ˈsetl"),
    ("severe", "adj. 严重的；严厉的", "sɪˈvɪər"),
    ("shadow", "n. 影子；阴影", "ˈʃædəʊ"),
    ("shallow", "adj. 浅的；肤浅的", "ˈʃæləʊ"),
    ("shelter", "n. 避难所 v. 庇护", "ˈʃeltər"),
    ("shift", "v. 转移 n. 转变", "ʃɪft"),
    ("shortage", "n. 不足；短缺", "ˈʃɔːrtɪdʒ"),
    ("shrink", "v. 收缩；缩小", "ʃrɪŋk"),
    ("signal", "n. 信号 v. 发信号", "ˈsɪɡnl"),
    ("significant", "adj. 重要的；显著的", "sɪɡˈnɪfɪkənt"),
    ("simplify", "v. 简化", "ˈsɪmplɪfaɪ"),
    ("simulate", "v. 模拟；模仿", "ˈsɪmjuleɪt"),
    ("simultaneous", "adj. 同时的", "ˌsɪmlˈteɪniəs"),
    ("site", "n. 地点；网站", "saɪt"),
    ("sketch", "n. 草图 v. 素描", "sketʃ"),
    ("skill", "n. 技能；技巧", "skɪl"),
    ("slavery", "n. 奴隶制", "ˈsleɪvəri"),
    ("slice", "n. 薄片 v. 切片", "slaɪs"),
    ("slight", "adj. 轻微的；微小的", "slaɪt"),
    ("slip", "v. 滑动 n. 疏忽", "slɪp"),
    ("smooth", "adj. 光滑的；平稳的", "smuːð"),
    ("social", "adj. 社会的；社交的", "ˈsəʊʃl"),
    ("sole", "adj. 唯一的 n. 鞋底", "səʊl"),
    ("solid", "adj. 固体的；可靠的", "ˈsɒlɪd"),
    ("solution", "n. 解决方案；溶液", "səˈluːʃn"),
    ("solve", "v. 解决；解答", "sɒlv"),
    ("sophisticated", "adj. 复杂的；精密的", "səˈfɪstɪkeɪtɪd"),
    ("source", "n. 来源；源泉", "sɔːrs"),
    ("species", "n. 物种；种类", "ˈspiːʃiːz"),
    ("specify", "v. 明确；详细说明", "ˈspesɪfaɪ"),
    ("speculate", "v. 推测；投机", "ˈspekjuleɪt"),
    ("sphere", "n. 球体；领域", "sfɪər"),
    ("spiritual", "adj. 精神的；心灵的", "ˈspɪrɪtʃuəl"),
    ("stable", "adj. 稳定的 n. 马厩", "ˈsteɪbl"),
    ("standard", "n. 标准 adj. 标准的", "ˈstændərd"),
    ("statistic", "n. 统计数据", "stəˈtɪstɪk"),
    ("status", "n. 地位；状态", "ˈsteɪtəs"),
    ("steady", "adj. 稳定的；持续的", "ˈstedi"),
    ("stimulate", "v. 刺激；激励", "ˈstɪmjuleɪt"),
    ("strategy", "n. 战略；策略", "ˈstrætədʒi"),
    ("strength", "n. 力量；优点", "streŋθ"),
    ("stress", "n. 压力；强调 v. 强调", "stres"),
    ("stretch", "v. 伸展；延伸", "stretʃ"),
    ("strict", "adj. 严格的；严厉的", "strɪkt"),
    ("strike", "v. 罢工；打击", "straɪk"),
    ("structure", "n. 结构 v. 构建", "ˈstrʌktʃər"),
    ("struggle", "v./n. 斗争；奋斗", "ˈstrʌɡl"),
    ("stuff", "n. 东西 v. 填满", "stʌf"),
    ("submit", "v. 提交；服从", "səbˈmɪt"),
    ("substance", "n. 物质；实质", "ˈsʌbstəns"),
    ("substitute", "n. 替代品 v. 替代", "ˈsʌbstɪtjuːt"),
    ("succeed", "v. 成功；继承", "səkˈsiːd"),
    ("sufficient", "adj. 足够的；充分的", "səˈfɪʃnt"),
    ("suggest", "v. 建议；暗示", "səˈdʒest"),
    ("suit", "n. 套装 v. 适合", "sjuːt"),
    ("summarize", "v. 总结；概括", "ˈsʌməraɪz"),
    ("summit", "n. 峰会；顶峰", "ˈsʌmɪt"),
    ("superior", "adj. 优越的 n. 上司", "suːˈpɪəriər"),
    ("supplement", "n. 补充 v. 增补", "ˈsʌplɪment"),
    ("supply", "v./n. 供给；供应", "səˈplaɪ"),
    ("support", "v./n. 支持；供养", "səˈpɔːrt"),
    ("suppose", "v. 假设；认为", "səˈpəʊz"),
    ("suppress", "v. 镇压；抑制", "səˈpres"),
    ("supreme", "adj. 最高的；至上的", "suːˈpriːm"),
    ("surface", "n. 表面 adj. 表面的", "ˈsɜːrfɪs"),
    ("surplus", "n. 剩余 adj. 过剩的", "ˈsɜːrpləs"),
    ("surrender", "v. 投降；放弃", "səˈrendər"),
    ("surround", "v. 包围；围绕", "səˈraʊnd"),
    ("survey", "n. 调查 v. 调查", "ˈsɜːrveɪ"),
    ("survive", "v. 幸存；存活", "səˈvaɪv"),
    ("suspect", "v. 怀疑 n. 嫌疑犯", "səˈspekt"),
    ("suspend", "v. 暂停；悬挂", "səˈspend"),
    ("sustain", "v. 维持；承受", "səˈsteɪn"),
    ("swallow", "v. 吞咽 n. 燕子", "ˈswɒləʊ"),
    ("swear", "v. 发誓；咒骂", "sweər"),
    ("symbol", "n. 符号；象征", "ˈsɪmbl"),
    ("sympathy", "n. 同情；赞同", "ˈsɪmpəθi"),
    ("symptom", "n. 症状；征兆", "ˈsɪmptəm"),
    ("system", "n. 系统；体制", "ˈsɪstəm"),
    ("tackle", "v. 处理；对付", "ˈtækl"),
    ("talent", "n. 天赋；人才", "ˈtælənt"),
    ("target", "n. 目标 v. 瞄准", "ˈtɑːrɡɪt"),
    ("tax", "n. 税 v. 征税", "tæks"),
    ("technical", "adj. 技术的；专业的", "ˈteknɪkl"),
    ("technique", "n. 技术；技巧", "tekˈniːk"),
    ("temporary", "adj. 临时的；暂时的", "ˈtempərəri"),
    ("tend", "v. 倾向于；照顾", "tend"),
    ("tendency", "n. 趋势；倾向", "ˈtendənsi"),
    ("tension", "n. 紧张；张力", "ˈtenʃn"),
    ("terminal", "n. 终端 adj. 末端的", "ˈtɜːrmɪnl"),
    ("territory", "n. 领土；领域", "ˈterɪtəri"),
    ("threat", "n. 威胁；恐吓", "θret"),
    ("thrive", "v. 繁荣；茁壮成长", "θraɪv"),
    ("tidy", "adj. 整洁的 v. 整理", "ˈtaɪdi"),
    ("tissue", "n. 组织；纸巾", "ˈtɪʃuː"),
    ("title", "n. 标题；头衔", "ˈtaɪtl"),
    ("tolerance", "n. 容忍；宽容", "ˈtɒlərəns"),
    ("topic", "n. 话题；主题", "ˈtɒpɪk"),
    ("torture", "v./n. 折磨；拷问", "ˈtɔːrtʃər"),
    ("trace", "v. 追踪 n. 痕迹", "treɪs"),
    ("tradition", "n. 传统；惯例", "trəˈdɪʃn"),
    ("transfer", "v. 转移；调动", "trænsˈfɜːr"),
    ("transform", "v. 转变；改造", "trænsˈfɔːrm"),
    ("transition", "n. 过渡；转变", "trænˈzɪʃn"),
    ("translate", "v. 翻译；转化", "trænsˈleɪt"),
    ("transmit", "v. 传输；传播", "trænzˈmɪt"),
    ("transparent", "adj. 透明的；坦率的", "trænsˈpærənt"),
    ("trend", "n. 趋势；倾向", "trend"),
    ("trial", "n. 审判；试验", "ˈtraɪəl"),
    ("trigger", "v. 触发 n. 扳机", "ˈtrɪɡər"),
    ("triumph", "n. 胜利 v. 获胜", "ˈtraɪʌmf"),
    ("tropical", "adj. 热带的", "ˈtrɒpɪkl"),
    ("trust", "n./v. 信任；信赖", "trʌst"),
    ("tumor", "n. 肿瘤", "ˈtjuːmər"),
    ("turbulent", "adj. 动荡的；混乱的", "ˈtɜːrbjələnt"),
    ("ultimate", "adj. 最终的；根本的", "ˈʌltɪmɪt"),
    ("undergo", "v. 经历；遭受", "ˌʌndərˈɡəʊ"),
    ("underline", "v. 强调；在…下划线", "ˌʌndərˈlaɪn"),
    ("undertake", "v. 承担；从事", "ˌʌndərˈteɪk"),
    ("unemployment", "n. 失业", "ˌʌnɪmˈplɔɪmənt"),
    ("unify", "v. 统一；使一致", "ˈjuːnɪfaɪ"),
    ("unique", "adj. 独特的；唯一的", "juːˈniːk"),
    ("universal", "adj. 普遍的；全世界的", "ˌjuːnɪˈvɜːrsl"),
    ("update", "v. 更新 n. 更新", "ʌpˈdeɪt"),
    ("upgrade", "v. 升级 n. 升级", "ʌpˈɡreɪd"),
    ("upright", "adj. 直立的；正直的", "ˈʌpraɪt"),
    ("urban", "adj. 城市的", "ˈɜːrbən"),
    ("urge", "v. 催促 n. 冲动", "ɜːrdʒ"),
    ("urgent", "adj. 紧急的；迫切的", "ˈɜːrdʒənt"),
    ("utilize", "v. 利用", "ˈjuːtɪlaɪz"),
    ("utmost", "adj. 最大的 n. 极限", "ˈʌtməʊst"),
    ("vacant", "adj. 空的；空闲的", "ˈveɪkənt"),
    ("vague", "adj. 模糊的；含糊的", "veɪɡ"),
    ("valid", "adj. 有效的；合理的", "ˈvælɪd"),
    ("value", "n. 价值 v. 重视", "ˈvæljuː"),
    ("vanish", "v. 消失；消散", "ˈvænɪʃ"),
    ("variable", "adj. 多变的 n. 变量", "ˈveəriəbl"),
    ("venture", "n. 冒险 v. 敢于", "ˈventʃər"),
    ("verify", "v. 核实；证实", "ˈverɪfaɪ"),
    ("version", "n. 版本", "ˈvɜːrʃn"),
    ("vertical", "adj. 垂直的", "ˈvɜːrtɪkl"),
    ("victim", "n. 受害者；牺牲品", "ˈvɪktɪm"),
    ("violence", "n. 暴力；暴行", "ˈvaɪələns"),
    ("virtual", "adj. 虚拟的；实质上的", "ˈvɜːrtʃuəl"),
    ("virtue", "n. 美德；优点", "ˈvɜːrtʃuː"),
    ("vision", "n. 视力；远见", "ˈvɪʒn"),
    ("vital", "adj. 至关重要的；生命的", "ˈvaɪtl"),
    ("vivid", "adj. 生动的；鲜明的", "ˈvɪvɪd"),
    ("vocabulary", "n. 词汇；词汇量", "vəˈkæbjələri"),
    ("volume", "n. 卷；体积；音量", "ˈvɒljuːm"),
    ("voluntary", "adj. 自愿的；志愿的", "ˈvɒləntri"),
    ("volunteer", "n. 志愿者 v. 自愿", "ˌvɒlənˈtɪər"),
    ("vote", "v./n. 投票；选举", "vəʊt"),
    ("vulnerable", "adj. 易受伤的；脆弱的", "ˈvʌlnərəbl"),
    ("wage", "n. 工资 v. 发动", "weɪdʒ"),
    ("wander", "v. 漫步；徘徊", "ˈwɒndər"),
    ("warrant", "v. 保证 n. 许可证", "ˈwɒrənt"),
    ("wealth", "n. 财富；丰富", "welθ"),
    ("weapon", "n. 武器", "ˈwepən"),
    ("welfare", "n. 福利；幸福", "ˈwelfeər"),
    ("whisper", "v./n. 低语；耳语", "ˈwɪspər"),
    ("whistle", "v. 吹口哨 n. 口哨", "ˈwɪsl"),
    ("widespread", "adj. 广泛的；普遍的", "ˈwaɪdspred"),
    ("withdraw", "v. 撤回；提取", "wɪðˈdrɔː"),
    ("witness", "n. 目击者 v. 目击", "ˈwɪtnɪs"),
    ("worship", "v./n. 崇拜；敬神", "ˈwɜːrʃɪp"),
    ("worthwhile", "adj. 值得的", "ˌwɜːrθˈwaɪl"),
    ("wreck", "v. 破坏 n. 残骸", "rek"),
    ("yield", "v. 生产；屈服 n. 产量", "jiːld"),
    ("youth", "n. 青年；青春", "juːθ"),
    ("xenophobia", "n. 仇外；排外情绪", "ˌzenəˈfəʊbiə"),
    ("zone", "n. 地区；区域", "zəʊn"),
]
